# Firebase Hosting GitHub Action Workflow
# Docs: https://firebase.google.com/docs/hosting/github-integration

name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js (adjust version if your project uses a different one)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build your project
      - name: Build project
        run: npm run build

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.7.0   # use stable version
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATTENDIFY_D5487 }}
          channelId: live
          projectId: attendify-d5487
